### ISSUE TITLE
Suggest missions

### ISSUE THREAD

**Issue by n0dane** [unitedoperations/uo-discordbot#16]
As a GM, could it be interesting to see what missions the player base wants to play.
So a  function where the player can write to the bot, and it remembers and stores the details.

a GM (or regular) can then ask the bot for suggestions, and the bot will list in list what missions the players want to play.

**Comment by callensm** [comment]
Can you give me an example of the command?

**Comment by n0dane** [comment]
Not sure if it should have its own channel, or if you can send messages directly to the bot.

but something like

/missions list | Shows all missions on the server.
/missions list 20-50 | Shows all missions on the server with max player count between 20 and 50.
/next mission id or string | id, should be from the two above lists, and string should just be a text string just like what people do in the mission "CO20 Poda" 

the list, could also have buttons that when pressed adds them to the list.

/missions Show | will show missions added to the suggestion list

**Comment by callensm** [comment]
Oh I see! I'm already in the middle of implementing a command for pulling mission file important from the FTP server so I can amend this to that command :)

**Comment by callensm** [comment]
While there is the ability to issue `telnet` commands to Teamspeak or use the Teamspeak SDK to directly get information from and interface with the server, the majority of missions are chosen by the GM or admin without the consideration of the player-base.

The functionality to search all primary server missions by name or keywords is already built in and accessible by the `!missions` command. I would be fine with implementing an extension to search by player count as well, but I don't see a full-blown mission suggestion feature being used in a capacity that would make it useful as @PaxJaromeMalues pointed out.
