### ISSUE TITLE
Ready - Seeding the server, but in a bot...

### ISSUE THREAD

**Issue by n0dane** [unitedoperations/uo-discordbot#17]
I think one of our biggest problems is seeding the server. When people join Teamspeak, and see that no one, or just a few are on the server, most will just do something else for the night. I for one have gotten enough of playing low count missions, and as such i'm a part of the problem, as i won't seed the server.

I propose that you can tell the bot that you are ready to play.

The bot will then collect this information and when it reaches 20, send out a message to all "ready" players, that there is now 20 signed up, and that they should get their ass on the server.

Extra features could be something like

"/ready 25" | The bot will poke you when 25 players are ready to play
"/ready off" | The pot will take you off the list
"/ready list" | The bot will poke you a list of the players that are on the list, and when they said that they were ready
"/ready time 20:00" | This tells the bot that you are ready to play from 20:00 Z

The bot should take everyone off the list after midnight 24:00Z (or something like that...)

**Comment by PaxJaromeMalues** [comment]
IDK about the /ready _n_ command. With the 25 players the server can be considered as seeded.
I would presume the seeding range from 0-15.
Maybe rather ommit this command and make the bot constantly (every 10mins or so) 'spam' the player a small message with <playersOnServer> and <playersInPrepQueue> or something alike.

**Comment by callensm** [comment]
@PaxJaromeMalues I'm assuming the 25 was an example but I understand the intent, and you raise a good point. It wouldn't be difficult to add that feature to the bot, however, the method in which the bot pulls the primary server data has the potential to be delayed but up to 5-10 minutes because the website I pull it from is delayed. During that time player counts can fluctuate a lot and be misleading.

I do like the idea of a "pending players" type of waiting listing for the server though. I'll look into it.

**Comment by n0dane** [comment]
For me, the main feature is that i can tell it.. okay when there is 40 on the server, let me know.

I know that i'm an ass, but to be honest, i just don't enjoy playing arma with sub 40 players. So i'm just gonna wait until we hit that number. :)

**Comment by callensm** [comment]
Partial implementation was complete on `dev` branch 
`#60b45de7d6701f11cbacaaff356e2b02a17213cb`

The remainder of this request will be looked at if the current changes seem to be positive.

**Comment by VyMajoris** [comment]
As a variation/upgrade of this command:

Instead of only counting the amount of people in the server, count the people who are subscribed(waiting for a poke) and those in the server. Maybe also count those in the Teamspeak waiting room channel(I don't know of that's possible).

**Comment by callensm** [comment]
Interacting with TeamSpeak through the bot is on the roadmap but not yet a clean up option for doing so to make it worth the effort.

Seeing the player count on the server is already available through the `!primary` command.

Adding the ability to see the number of players waiting for a player count alert to the backlog. Should be done within the day.

**Comment by callensm** [comment]
Done.
fe4519c2b43df7d76fa1eef8bdec523bc6709228
