### ISSUE TITLE
bot notification rebuild

### ISSUE THREAD

**Issue by PaxJaromeMalues** [unitedoperations/uo-discordbot#3]
hello dev, good stuffs sofar!

please consider to... consider... the following:

Notification Mention:
- Event Notifications with @Group only once per week when eventday is more distant than 1 week; when eventday is closer than 2 days one @group notification each day before the event.
- Notification of new mission as is.
- otherwise I would suggest to keep to posting other bot messages in ArmA3 chat on a regular basis but without @mention so people who search for info find it fast and others not liking the mentions will not be bothered.

**Comment by callensm** [comment]
Thanks for the suggestion (and for using github like we've been asking). We're currently looking at ways to reduce annoyance from the group mentioning in the alerts and this will definitely be considered. Adding it to our backlog.
