### ISSUE TITLE
UOAF Pickup Flight

### ISSUE THREAD

**Issue by lba1986** [unitedoperations/uo-discordbot#30]
UO Discord bot needs to notify players that a BMS/DCS flight is happening.

Here is the current method used inform players in the #UOAF_Flights channel that a pickup flight is starting.

_@UOAF I'm hosting a "BMS/DCS" flight at "xx:xxz" time/date using "x" theater/modules", would anyone like to join?_

At this point people typically respond about their ability to join. I would like to see the UO Bot handle both notification and the signup process. Also the bot would assign @UOAF tags to those that wish to be notified of events/pickups.

**Command Requirements**
Joining the @UOAF group
!join_group UOAF 

Leaving the @UOAF group
!leave_group UOAF

Joining a pickup flight
!join "xxxx"
!j "xxxx"

Creating a pickup flight _This is a command that will start a pm chain. In the pm chain, the bot will ask for the flight sim, time/date, theater/modules/details._
!create_flight
After the bots gathers the three details(Game/Time/Details), it will post the event in the #uoaf_flights channel with a four digit number attached. Players then use the !join or !j command along with the pickup number to rsvp.

The bot will then notify players of the event using @uoaf in increments of 1day/1 hour/1 minute before start time. The bot will also PM users that RSVP'd in these increments.

**Comment by callensm** [comment]
Majority of functionality complete in 06758998c44afbdec396afaec47c70995630f92c

Missing time/date argument parsing and notifications
