### ISSUE TITLE
Spam Prevention

### ISSUE THREAD

**Issue by TinfoilHate** [unitedoperations/uo-discordbot#4]
Allow a limited number of maximum channel/group updates per amount of time, i.e. 2 updates in 10 minutes. The reasoning behind this is to prevent people on the server from spamming the channel/group by changing missions frequently.

**Comment by callensm** [comment]
Already in place.
Server information scrapping occurs once every 5 minutes, but can be configured otherwise by Discord admins, producing a maximum of 1 update per 5 minutes.

**Comment by callensm** [comment]
Is that what you're referring to?

**Comment by TinfoilHate** [comment]
Specifically, yeah, that would do it.  Basically the only concern was regarding the frequency of updates if the mission rapidly changed. Given the 5 minute interval, this is a non-issue.
