### ISSUE TITLE
give classes and levels to the bot notifications to mitigate double notifies

### ISSUE THREAD

**Issue by PaxJaromeMalues** [unitedoperations/uo-discordbot#40]
#### Is it related to a problem?

Doubled notifications on the same timestamp.

#### Description of suggestion

Add Type, Class and Level values to notifications.

Example:

type_Event_Single
is of higher level than a notification of
type_Event_Reoccuring

A combination of two types of notifications which will be posted with the same timestamp [i.e. 1900Z 01AUG19] should be evaluated something likes this:

bot recognizes that 2 notifications are to be sent for the same date timestamp >> is _notification_ of type _arma_ ? **>yes>** is _notification_ of type _type_Event_Single_ ? **>yes>** the notification with _type_Event_Single_ will be prioritized over the notification with _type_Event_Reoccuring_.

#### Screenshots

https://imgur.com/l1iJTLH

**Comment by PaxJaromeMalues** [comment]
Just to clarify, override is only triggered when `timestamp` AND `type` are the same in both notifications and one of both/multiple notifications overrides via its `type_Event_Single` value. Wasn't sure if I was clear on that.

**Comment by callensm** [comment]
In the current system, notifications are scheduled based on times given as environment variables to the application. For each calendar event, its configured to launch an alert at the intervals:

- 7 days
- 2 days
- 12 hours
- 2 hours
- 5 minutes

Each of these notifications are scheduled separately at the time of event creation and aren't touched by the bot at all afterwards. In that sense, they are all independent "single" event notifications. There is no concept in the current system of a "reoccurring" or "single" event - all events are handled exactly the same after being read from the forum's calendar API.

For the next update, I have reduced the amount of notifications for a given event from the 5 listed above to 4 that are more spread out. The incident where the bot posted 3 or 4 in a row the other day was an anomaly that hasn't happened before, but all of those notifications were for different events, the bot was just posting the notifications as properly scheduled for each one...just so happened that they all needed one at the same time.
