### ISSUE TITLE
!lfg list auto post

### ISSUE THREAD

**Issue by PaxJaromeMalues** [unitedoperations/uo-discordbot#6]
Check against existing list.
1. Auto post creation of a new LFG group in the lfg discord channel.
2. Periodically (2h?) make McBotface run a check of !lfg list and make him save it into a file. Should the content be the same, make McBotface remain silent (no auto lfg status post) if the content changed make him post a list of open LFGs.
No @ mention on either post.

Both posts should be one liners if possible.

**Comment by PaxJaromeMalues** [comment]
You could make point 1 require input from the group owner to avoid lfg creation posts by accidentally created lfg groups.

**Comment by callensm** [comment]
Could you give an example post from the bot for this feature

**Comment by PaxJaromeMalues** [comment]
None of the posts should be in #general. Both should be in: #looking-for-group without any @mention.

Example post for 1:
Hello there, the group ''<name>'' with the ID ''<id>'' has been created and needs ''<# needed>'' players, Have Fun!

Example post as response to group owner:
You crated the group secrethitler, do you want the bot to post a creation message in #looking-for-group?

Example Post for 2:
Automated LFG Group Update: Currently the following groups are open: secrethitler, arma, sellingdrugs.

Kind regards
Pax

**Comment by callensm** [comment]
![image](https://user-images.githubusercontent.com/13121516/44876124-22801700-ac6e-11e8-9efe-3cc79dd59fe1.png)

@PaxJaromeMalues 
Sample implementation

**Comment by callensm** [comment]
Automated notifications to LFG channel:
af463e971eb51c40801b4d3ebb879119f68d29d5
